apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
    wg: "true"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: nginx
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: busybox
      image: alpine/curl
      command: ["sleep", "3600"]
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx 
    wg: "true"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: busybox
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: nginx
      image: nginx
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80